### ISSUE TITLE
lurch 0.6.7 with pidgin 2.12.0

### ISSUE THREAD

**Issue by heavytull** [gkdr/lurch#110]
i tried lurch 0.6.7, with conversations.im in pidgin and messages from a conversations.im messenger to                                                  
the a conversations.im account through pidgin don't get through. Pidgin says:

"(16:47:52) user213@conversations.im: I sent you an OMEMO encrypted message but your client doesn’t seem to support that. Find more information on https://conversations.im/omemo".                                                                                              

By messaging the other way, conversations.im messenger displays the contents but with a warning saying that it's unencrypted. The plugin is well activated, in the plugins window of pidgin and i even restarted it. Also in pidgin conversations.im contacts always appear disconnected and marked "unauthorized".

when running pidgin with debug option, when receiving a message it output among other stuff:
lurch: received omemo message that does not contain a key for this device, skipping.

But i don't see where and how to enter the key i can find in conversations.im.

**Comment by gkdr** [comment]
Hi, does this issue still persist? It sounds like your devicelist node did not get updated, which might have simply resolved by itself by now.

**Comment by jesse-git** [comment]
I started getting the same message, with a couple of differences, when I upgraded from Conversations 1.23.8 to 2.2.3 . Nothing else about my environment changed.

Everything works fine for me unless I am logged on in Pidgin at the same time as in Conversations, with my buddy also using Conversations. When my Conversations attempts to send an OMEMO encrypted message to my Pidgin, I receive the error. I was using lurch 0.6.6 in Pidgin.

**Comment by gkdr** [comment]
By "the same message", do you also mean the same message on the debug log? So like this, taken from the OP?

>lurch: received omemo message that does not contain a key for this device, skipping.

**Comment by jesse-git** [comment]
I forgot to check the debug window. No, I don't see that error. I do see another error:

> (19:28:37) jabber: XML parser error for JabberStream 09F14048: Domain 3, code 100, level 1: xmlns: URI eu.siacs.conversations.axolotl is not absolute

My buddies don't appear as unauthorized, either. So is this a separate issue? I can create a new one. Any way this would this cause `I sent you an OMEMO encrypted message but your client doesn’t seem to support that.`?

**Comment by heavytull** [comment]
gkdr what do you mean by "still persist"? i reported about v. 0.6.7 and today this is still the latest version. With the setup being same as for my OP this still doesn't work and i still get the same error message.

**Comment by gkdr** [comment]
It's been a while, so I'm just going to close this. If it still doesn't work, please open a new issue.
