### ISSUE TITLE
Lurch not usable in Pidgin 2.13

### ISSUE THREAD

**Issue by alexolog** [gkdr/lurch#114]
From the debug log:
```
>> (00:32:12) plugins: C:\Program Files (x86)\Pidgin\plugins\lurch.dll is not usable because the 'purple_init_plugin' symbol could not be found.  Does the plugin call the PURPLE_INIT_PLUGIN() macro?
```

**Comment by gkdr** [comment]
There was a windows build that did not have the compile flag set. Are you using the newest version of the plugin? Did it work before upgrading to Pidgin 2.13?

**Comment by alexolog** [comment]
Got the latest DLL from the releases.  Seems to be working.  Closing.
