### ISSUE TITLE
Error running lurch on debian sid

### ISSUE THREAD

**Issue by angelabad** [gkdr/lurch#116]
Hi, I compiled lurch with README instructions and did make install-home, so it doesnt work on mi pidgin.
I ran pidgin in debug mode, and allways I have this message:

(11:50:45) prefs: Reading /home/angel/.purple/prefs.xml
(11:50:45) prefs: Finished reading /home/angel/.purple/prefs.xml
(11:50:45) prefs: purple_prefs_get_path: Unknown pref /pidgin/browsers/command
(11:50:45) dbus: okkk
(11:50:45) plugins: probing /home/angel/.purple/plugins/lurch.so
(11:50:45) plugins: /home/angel/.purple/plugins/lurch.so is not loadable: libjabber.so.0: cannot open shared object file: No such file or directory
(11:50:45) plugins: probing /usr/lib/pidgin/cap.so
(11:50:45) plugins: probing /usr/lib/pidgin/extplacement.so
(11:50:45) plugins: probing /usr/lib/pidgin/history.so
(11:50:45) plugins: probing /usr/lib/pidgin/timestamp_format.so
(11:50:45) plugins: probing /usr/lib/pidgin/xmppdisco.so

Versions used:
pidgin - 2.13.0-2
pidgin-data - 2.13.0-2
pidgin-otr - 4.0.2-2
libpurple-bin - 2.13.0-2
libpurple-dev - 2.13.0-2
libpurple0 - 2.13.0-2

If you need more info, please contact me.

Cheers

**Comment by powerman** [comment]
Same on Gentoo:
```
$ ls -l /usr/lib64/purple-2/{libjabber,lurch}*
lrwxrwxrwx 1 root root     18 июн 20 19:49 /usr/lib64/purple-2/libjabber.so -> libjabber.so.0.0.0
lrwxrwxrwx 1 root root     18 июн 20 19:49 /usr/lib64/purple-2/libjabber.so.0 -> libjabber.so.0.0.0
-rwxr-xr-x 1 root root 446696 июн 20 19:49 /usr/lib64/purple-2/libjabber.so.0.0.0
-rwxr-xr-x 1 root root 580656 сен  4 07:25 /usr/lib64/purple-2/lurch.so
$ pidgin -d |& grep lurch
(07:45:23) plugins: probing /usr/lib64/purple-2/lurch.so
(07:45:23) plugins: /usr/lib64/purple-2/lurch.so is not loadable: libjabber.so.0: cannot open shared object file: No such file or directory
```

**Comment by powerman** [comment]
I've worked around this issue by adding `/usr/lib64/purple-2` to `/etc/ld.so.conf` (but I'm not sure it right thing to do).

**Comment by powerman** [comment]
More clean way is to run `LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib64/purple-2 pidgin` instead of modifying `/etc/ld.so.conf`.

**Comment by gkdr** [comment]
This should have been fixed by merging the pull request referencing this issue, so I'm closing it.
