### ISSUE TITLE
Lurch/Pidgin not syncing with Android clients.

### ISSUE THREAD

**Issue by ProfP30** [gkdr/lurch#117]
Hello,
 I want to use OMEMO in Pidgin Portable.
 It works when I sync with e.g. Gajim for Windows, but I cannot see my crypted OMEMO messages in Android XMPP clients like Conversation or Pix-Art Messenger (https://github.com/kriztan/Pix-Art-Messenger).
The XMPP Message Carbons Plugin is also activated.

In Gajim I have a dialog to sign OMEMO fingerprints.
How does Pidgin respectively Lurch handle fingerprints (in Gajim there is dedicated dialog for this).

I can see my encrypted messages typed in Pidgin syncing with Gajim - OK.
I can see my encrypted messages typed in Gajim syncing with Pidgin - OK.
I can see my encrypted messages typed in Gajim syncing with Android Client - OK.
I cannot see my encrypted messages typed in Pidgin/Lurch syncing with Android Client - NOT OK.

-> Why are my OMEMO Pidgin-messages not synced with the Android clients?

Versions: 
    Device: Samsung s7 (herolte) with LineageOS 14.1 (based on Android 7.1)
    Pidgin (Windows) Version: Pidgin 2.13.0 (libpurple 2.13.0)
    OMEMO Plugin Version "lurch": 0.6.7 (https://github.com/gkdr/lurch)
    Windows version: Windows 10 version 1803
    Conversations for Android 2.2.8+fcr
    XMPP Message Carbons 0.1.4

Best Regards
Prof.P

**Comment by gkdr** [comment]
There seems to be an issue with Pidgin Portable (see e.g. #106). Have you tried the regular version too?

**Comment by Kudalufi** [comment]
Lurch, at least v0.6.8, works just fine in regular Pidgin to encrypt conversations with Pix-Art Messenger

**Comment by gkdr** [comment]
Closing this old issue for age and inactivity. If you come across this problem again, please create a new one.
