### ISSUE TITLE
"Failed to access axc db" whatever action I try

### ISSUE THREAD

**Issue by jonasc** [gkdr/lurch#12]
Hy, I have compiled and activated the plugin in pidgin (2.11.0). If I type `/lurch help` in a window I just get `Failed to access axc db.` as a result. I've briefly scanned the code but I cannot locate what could be the problem here. Can you help?

**Comment by gkdr** [comment]
I assume this is an issue with the DB path. I added some debug output in cb081fd6a9509a2fcd23b61f6f31ed38324b3505, it should display the path it is looking for now. Can you tell me if it looks obviously wrong?

**Comment by jonasc** [comment]
It works now… very strange

**Comment by gkdr** [comment]
Oh, maybe it was something else that I did in that commit. In any case, I'm glad it works! I'll close this issue then, but if anything else doesn't work, just open a new issue.
(Or if it still seems broken and seems realted to this, you can still comment too.)

**Comment by EionRobb** [comment]
I wonder if this will help on windows too
