### ISSUE TITLE
undefined symbol: mxmlGetLastChild

### ISSUE THREAD

**Issue by LiohMoeller** [gkdr/lurch#137]
I have built the plugin from source after building mxml (which was missing on my machine) from here: https://github.com/michaelrsweet/mxml

The build of the plugin was successful but when I try to load it, I got an error like:

lurch.so is not loadable: undefined symbol: mxmlGetLastChild

**Comment by gkdr** [comment]
I don't think this is a version issue, as this function still exists in the newest 3.x release of mxml: https://www.msweet.org/mxml/mxml.html#mxmlGetLastChild

If I remember correctly, when stuff fails at runtime like this it's usually a linking issue. Did you actually install mxml as a system library after building it? (Which distribution are you using, by the way? mxml is usually available through the package repos.) I can also imagine that it's not being picked up by `pkg-config`. Do `pkg-config --cflags mxml` and `pkg-config --libs mxml` yield anything useful?

You could also either try the _dev_ branch, or update the `libomemo` submodule to the newest commit. This specific function is not used in my code any more, but I suspect you'll just trip over the next one.

**Comment by LiohMoeller** [comment]
Thanks for the hints. It was actually a pkg-config issue which I was now able to solve.

**Comment by gkdr** [comment]
You're welcome! Glad I could help.
