### ISSUE TITLE
Crash when sending OMEMO massage

### ISSUE THREAD

**Issue by Sanyy** [gkdr/lurch#140]
Starting program: /usr/bin/pidgin 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffdbe21700 (LWP 16155)]
[New Thread 0x7fffdb620700 (LWP 16156)]
[New Thread 0x7fffdae1f700 (LWP 16157)]
[Thread 0x7fffdb620700 (LWP 16156) exited]

Thread 1 "pidgin" received signal SIGSEGV, Segmentation fault.
0x00007fffe9688cfb in jabber_send_signal_cb ()
   from /usr/lib/purple-2/libjabber.so.0
...
#0  0x00007fffe9688cfb in jabber_send_signal_cb ()
    at /usr/lib/purple-2/libjabber.so.0

**Comment by gkdr** [comment]
Did you install any other plugins at the same time? Is there a complete version of that stacktrace? Do you see any errors in the debug log?

**Comment by Sanyy** [comment]
Some basic bundled plugin was enabled but there is no crash anymore the system might just needed a restart after compiling it. don't know.

Where are the log files?(ubuntu 18.04)

sorry and thanx.

**Comment by gkdr** [comment]
That's weird. By "debug log" I meant the Pidgin debug log (Help > Debug Window). But I assume you cannot reproduce it anymore?

**Comment by Sanyy** [comment]
I can't. I think we can close this.
