### ISSUE TITLE
cannot activate plugin on ubuntu 16.04

### ISSUE THREAD

**Issue by deknos** [gkdr/lurch#15]
Hi, 
i compiled the plugin according to your instructions, but i cannot activate lurch in the plugin menu, but it is there. pidgin version is 1:2.10.12-0ubuntu5.1.

Any idea?
Otherwise, thanks for your work

**Comment by gkdr** [comment]
After talking in IRC, this was resolved in 828a82e57a722913a0e4491c388455e84bb1e07a, which is on a different branch.

There was a problem with opening the semaphore, but apparently, libpurple does not even use threads and I was mislead my some gdb output. I commented out all the semaphore code, after some cleaning up I will merge this into the main branch, as it also increases cross-compatibility.
