### ISSUE TITLE
Visibility problem

### ISSUE THREAD

**Issue by rosso-** [gkdr/lurch#154]
Build and install successful, but
can't see this plugin in plugin list window of Pidgin.

**Comment by gkdr** [comment]
- what is your OS?
- what is your pidgin version?
- how did you install it after building?
- open the debug window, and then while it is open open the plugin window. does the debug log mention the lurch plugin?

**Comment by rosso-** [comment]
- FreeBSD 12.1-RELEASE-p3 r359640
- pidgin-2.14.1
- build&install from README:
`git clone https://github.com/gkdr/lurch/
cd lurch
git submodule update --init --recursive
make install-home`
- Now it works, after rebuilding of pidgin and libpurple. 

Don't know what was the problem, but can confirm it works on FreeBSD 12.1

**Comment by gkdr** [comment]
cool, good to know, thanks :D glad that it worked in the end.
