### ISSUE TITLE
Name changing request

### ISSUE THREAD

**Issue by Neustradamus** [gkdr/lurch#158]
Can you rename your repository to be more linked to pidgin/libpurple like other plugins?

Example: "purple-lurch" or "purple-omemo"?

After the renaming of the repository, redirections will be here, no lost.

- https://repology.org/project/lurch/versions
- https://repology.org/project/libpurple-lurch/versions
- https://repology.org/project/purple-plugin-lurch/versions
- https://repology.org/project/lurch-purple/versions
- https://repology.org/project/purple-lurch/versions

**Comment by gkdr** [comment]
i see how it might be less confusing if it's clear this is a libpurple plugin. the issue i see is that in the links you provided the "purple" part is not consistently in front of the plugin name, so i don't see any upsides to renaming the repository. this way, the repository name reflects the plugin name, and not some of the linux package names (but not others).
