### ISSUE TITLE
Displaying FPs (slightly) broken

### ISSUE THREAD

**Issue by turion** [gkdr/lurch#16]
When I'm typing `/lurch fp own`, my fingerprint is shown. It contains `:d` in one part, and this part is converted to a smiley. That's funny, but probably unintended :D

**Comment by gkdr** [comment]
I'll try to think of something. The "no formatting" flag didn't help, unfortunately - I'll probably just add some spaces.

**Comment by DreamFlasher** [comment]
Conversations and Gaijm show the fingerprint in 5 character blocks. I think lurch should follow the same pattern to make comparisons easier (and the colons everywhere don't help that much).

**Comment by gkdr** [comment]
I agree I should match the other programs' FP display format. Also a good time to get rid of the two additional characters in the front.
(I simply used libpurple's own fingerprint generation function instead of writing my own, which is why it doesn't quite match.)

**Comment by turion** [comment]
Awesome. Built and tested.
