### ISSUE TITLE
[0.7.0] Makefile pulls indirect dependencies (from libomemo and libaxc) into lurch without need to?

### ISSUE THREAD

**Issue by hartwork** [gkdr/lurch#164]
Hi!

While packaging lurch 0.7.0 for Gentoo it came to my attention that `Makefile` is still referencing some libraries as dependencies that seem to be dependencies of libomemo and libaxc now, but not lurch itself. If that's true — and `lddtree` output below seems to agree (due to linking with `--as-needed`) — then traces of these libraries can probably be remove from `Makefile` altogether:
- libxml2
- sqlite3
- mxml
- libgcrypt

What do you think?

For the `lddtree` output:

```console
# lddtree /var/tmp/portage/x11-plugins/lurch-0.7.0/image/usr/lib64/purple-2/lurch.so
/var/tmp/portage/x11-plugins/lurch-0.7.0/image/usr/lib64/purple-2/lurch.so (interpreter => None)
    libglib-2.0.so.0 => /usr/lib64/libglib-2.0.so.0
        libpcre.so.1 => /lib64/libpcre.so.1
        libpthread.so.0 => /lib64/libpthread.so.0
            ld-linux-x86-64.so.2 => /lib64/ld-linux-x86-64.so.2
    libomemo.so.0 => /usr/lib64/libomemo.so.0
        libmxml.so.1 => /usr/lib64/libmxml.so.1
        libsqlite3.so.0 => /usr/lib64/libsqlite3.so.0
            libm.so.6 => /lib64/libm.so.6
            libdl.so.2 => /lib64/libdl.so.2
            libz.so.1 => /lib64/libz.so.1
            libicui18n.so.68 => /usr/lib64/libicui18n.so.68
                libstdc++.so.6 => /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/libstdc++.so.6
                libgcc_s.so.1 => /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/libgcc_s.so.1
            libicuuc.so.68 => /usr/lib64/libicuuc.so.68
                libicudata.so.68 => /usr/lib64/libicudata.so.68
        libgcrypt.so.20 => /usr/lib64/libgcrypt.so.20
            libgpg-error.so.0 => /usr/lib64/libgpg-error.so.0
    libaxc.so.0 => /usr/lib64/libaxc.so.0
    libsignal-protocol-c.so.2 => /usr/lib64/libsignal-protocol-c.so.2
    libjabber.so.0 => /usr/lib64/purple-2/libjabber.so.0
        libxml2.so.2 => /usr/lib64/libxml2.so.2
        libgstreamer-1.0.so.0 => /usr/lib64/libgstreamer-1.0.so.0
            libgmodule-2.0.so.0 => /usr/lib64/libgmodule-2.0.so.0
            libunwind.so.8 => /usr/lib64/libunwind.so.8
            libdw.so.1 => /usr/lib64/libdw.so.1
                libbz2.so.1 => /lib64/libbz2.so.1
            libelf.so.1 => /usr/lib64/libelf.so.1
            librt.so.1 => /lib64/librt.so.1
        libgobject-2.0.so.0 => /usr/lib64/libgobject-2.0.so.0
            libffi.so.7 => /usr/lib64/libffi.so.7
    libc.so.6 => /lib64/libc.so.6
```

Best, Sebastian

**Comment by gkdr** [comment]
hi @hartwork,

are they not still a dependency for the statically linked case?

**Comment by hartwork** [comment]
That's an interesting point/question. Is the static linking case needed in 2021?

**Comment by EionRobb** [comment]
I use static linking for the Windows builds, if that's any fuel to the argument

**Comment by hartwork** [comment]
@EionRobb would shared libaries — DLLs — work for you?

**Comment by EionRobb** [comment]
@hartwork doesn't really work, no.
I mean, technically sure, but it's challenging enough trying to get people to copy 2 shared dll's for gcrypt into one folder and the lurch dll into another, let alone another 3 dlls.  And then it was even harder when the telegram plugin was using gcrypt and the two versions of gcrypt were conflicting with each other, ugh.

On WinPidgin it's always more preferable to have a single dll file that's one big blob of statically compiled deliciouness, from a user perspective.

If I can figure out how to get gcrypt statically compiled into the lurch.dll's then that would be my preference.

**Comment by hartwork** [comment]
@EionRobb thanks for elaborating.

**Comment by hartwork** [comment]
Closing as "not a bug". Please re-open if I'm mistaken.
