### ISSUE TITLE
I can't seem to read other people's devicelists

### ISSUE THREAD

**Issue by alex11star** [gkdr/lurch#170]
When I message people with Lurch I get "Even though an encrypted session exists, the recipient's devicelist is empty.The user probably uninstalled OMEMO, so you can add this conversation to the blacklist." Other people seem to be able to see my devices, but I can't see theirs. Any tips to troubleshoot?

**Comment by alex11star** [comment]
This has been fixed by installing https://github.com/gkdr/carbons

**Comment by gkdr** [comment]
Glad this issue resolved itself. :slightly_smiling_face:
