### ISSUE TITLE
Having lurch enabled in pidgin causes connections to reset

### ISSUE THREAD

**Issue by lukerb52** [gkdr/lurch#175]
`Lost connection with server: Connection reset` is the message that Pidgin gives me. This does not happen when lurch is turned off. The server I am using is Prosody.

**Comment by gkdr** [comment]
hi, thanks for the report! which version of prosody is it? i am usually testing locally using prosody, maybe they introduced a relevant change recently.

**Comment by lukerb52** [comment]
1:0.11.10-1
 Latest Arch Linux Version

**Comment by gkdr** [comment]
oh, i was still testing with the ancient 0.11.2, i'll see what happens after an update.
in the meantime, can you tell me when and where you see that message? is it the debug window? if so, could you paste what happens leading up to that message? i'm interested in the raw html. thanks!

**Comment by lukerb52** [comment]
This issue no longer happens. I'm not sure what changed, but another pidgin problem has come up that I will post in a new issue.
