### ISSUE TITLE
Displayed fingerprint doesn't match (two additional characters)

### ISSUE THREAD

**Issue by DreamFlasher** [gkdr/lurch#20]
/lurch show fp own

    05:39:5b:d1:1a:19:67:b9:31:af:b6:13:99:24:f4:42:82:04:eb:07:42:41:0b:6e:a8:92:b1:60:2e:bf:df:0f:22

Gajim shows:

    395bd11a1967b931 afb61399 24f44282 04eb0742 410b6ea8 92b1602e bfdf0f22

There's a 05 in the front too much.

**Comment by gkdr** [comment]
I'll deal with this issue together with #16, so I'll close this one.
