### ISSUE TITLE
lurch isnt showing under plugins / windows 10

### ISSUE THREAD

**Issue by razzor1984** [gkdr/lurch#26]
Hello, 
i tried to test it with an user which has windows 10. I looked into it, but when i follow the tutorial to put the dlls from this link https://eion.robbmob.com/lurch/  to this path  \AppData\Roaming\.purple\plugins 
The lurch plugin isnt showing under plugins (Did a couple of restarts of pidgin)
If i move the dlls to this directory path  - X:\Program Files\Pidgin\plugins  - nothing changes.

The approache with the carbons dll is working under windows i did see the plugin in pidgin.
(path  \AppData\Roaming\.purple\plugins )

Version of windows - 10 - 1607
pidgin version - 2.11.0

best regards Razzor

**Comment by TheForcer** [comment]
Had the same issue yesterday when installed both of the plugins. I got it working after putting the 3 .dll files (lurch.compat, libgcrypt20, libgpg-error) into the AppData plugins directory, as well as the root of the Pidgin installation (in your case: X:\Program Files\Pidgin\). The plugin showed up in the directory then.
I am not exactly sure if you need place only specific files into each of the directories, but its working this way.

**Comment by EionRobb** [comment]
I really need to put some instructions on the site, but the libgcrypt/libgpg-error dll's need to go into the `Program Files\Pidgin` folder, but the lurch-compat/lurch dll needs to go into the `Program Files\Pidgin\plugins` folder

**Comment by gkdr** [comment]
That's what I meant by saying "put them in the libpurple path" but I guess that's not very clear and I should write down the exact paths.

@razzor1984 Did the solutions suggested here work for you? It looks like the problem is that you put all the .dlls in the plugins directory, but the gcrypt ones need to go in the Pidgin directory,

**Comment by razzor1984** [comment]
@gdkr 
Yep worked flawless withe the description of TheForcer :)
Issue can now be closed.
