### ISSUE TITLE
Not receiving message when multiple devices are used for the same user

### ISSUE THREAD

**Issue by 2Belette** [gkdr/lurch#27]
Hi,

First many thanks for your plugin as I am trying to aggregate all my accounts to Pidgin, but XMPP is tricky because of OMEMO support.
I am testing it and it is almost working well but I have an issue I can easily reproduce.
I have Conversation + Pidgin on the same account both with OMEMO.
If I am sending message from Pidgin everything is OK, the messages from my correspondent are received on Conversation and Pidgin.
If I write a message from Conversation, if my correspondent is replying to me I only receive the message on Conversation and nothing on Pidgin.
This situation remains until I decide to write one word on Pidgin and send it and everything is working perfectly again (receiving the message from my correspondent in both devices)

Have you encounter the same issue?

**Comment by EionRobb** [comment]
Are you using the xmpp-carbons plugin?

**Comment by 2Belette** [comment]
Yes I am.
I tried to /carbons off and I got the same issue.
Do you think it is related to it?

On Sat, Feb 25, 2017 at 06:22:13AM -0800, Eion Robb wrote:
>Are you using the xmpp-carbons plugin?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gkdr/lurch/issues/27#issuecomment-282486913

-- 
Benoit

**Comment by gkdr** [comment]
My XMPP server currently seems to be down so I can't try to reproduce it, but yes, it is most likely a carbons issue. The usual behaviour of servers when carbons is disabled is to send the message to the last active device.
Are you sure your server supports carbons and is up to date? The plugin only parses the newest namespace (but on the other hand, it should never work then).

You could also look in the debug window and see if the carbons messages arrive at all.

**Comment by 2Belette** [comment]
Thanks for your reply.
I am using openfire, and I double checked and it is supporting carbons.
Will take a look on the debug side, is there any specific command to activate the debug? many thanks

**Comment by gkdr** [comment]
You can find the debug at _Help->Debug Window_ in Pidgin.
You should see the raw XML that XMPP receives and it would be interesting to see if the carbons messages arrive at all (in your case it should be a <message> with a <forwarded> node that has a <received> node with the carbons namespace inside of it).

**Comment by 2Belette** [comment]
Thanks.
I am receiving this message:

(12:13:11) jabber: XML parser error for JabberStream 0x2f96c00: Domain 
3, code 100, level 1: xmlns: URI eu.siacs.conversations.axolotl is not 
absolute
(12:13:11) carbons: Received carbon copy of a sent message.
(12:13:12) carbons: Received carbon copy with invalid sender! (Ignoring.)

(12:13:12) jabber: Recv (ssl)(399): <message type="chat" 
from="bel@xxx" 
to="bel@xxx/atyauj9hzj"><received 
xmlns="urn:xmpp:carbons:2"><forwarded 
xmlns="urn:xmpp:forward:0"><message xmlns="jabber:client" 
from="fre@xxx/phone" to="bel@xxx/phone" 
type="chat"><received xmlns="urn:xmpp:chat-markers:0" 
id="e45eaa99-b678-4c37-911b-613dba9c5037"/></message></forwarded></received></message>

(12:13:12) carbons: Received carbon copy of a received message.
(12:13:12) carbons: Received carbon copy with invalid sender! (Ignoring.)

On Sun, Feb 26, 2017 at 02:04:27AM -0800, Richard Bayerle wrote:
>You can find the debug at _Help->Debug Window_ in Pidgin.
>You should see the raw XML that XMPP receives and it would be interesting to see if the carbons messages arrive at all (in your case it should be a <message> with a <forwarded> node that has a <received> node with the carbons namespace inside of it).
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gkdr/lurch/issues/27#issuecomment-282545378

-- 
Benoit

**Comment by gkdr** [comment]
According to the XEP, the message must come from the same sender, and it seems to do that, and I must have broken the check (it works fine for me though, weird enough). Do you mind checking out the "debug" branch of carbons and trying again? (I will need the debug log output again too.)
Also, since it is related to the carbons plugin, would you mind opening an issue at the carbons repository and closing this one?

**Comment by 2Belette** [comment]
sure :) closing and re-opening at carbons repo
I git pulled and got the debug branch now, waiting for a friend to connect to make the test..
