### ISSUE TITLE
Interoperability with standard Omemo clients

### ISSUE THREAD

**Issue by DreamFlasher** [gkdr/lurch#3]
Please add interoperability with standard Omemo clients -- this is exactly what this is all about, that we have a standardized encryption so that users can freely pick their favorite client :)

**Comment by EionRobb** [comment]
I disagree, following the standard should be a higher priority. Other clients should follow the standard too.

**Comment by DreamFlasher** [comment]
Did you mean to write that you agree?

**Comment by EionRobb** [comment]
Depends what you mean by "standard omemo client":)

**Comment by DreamFlasher** [comment]
An Omemo client hat follows the Omemo standard ;)
Right now all existing Omemo clients follow the XEP specification. This one here (lurch) does not. So I'm saying it should do so in order to provide interop.

**Comment by gkdr** [comment]
Actually, none of the existing OMEMO clients follow the XEP specification (as I recently learned). And, to be fair, it is experimental.
The funny thing is that it makes it much easier for me to make them interoperate since I do not have to replace the wire protocol of the encrypted data after all.
So... I'm on it!

**Comment by DreamFlasher** [comment]
Holy shit, conversations, ChatSecure and Gajim don't follow XEP-0384? o_O Do you have more information on that? But fair point, it is experimental (http://xmpp.org/extensions/xep-0384.html)
So what did they implement and how did it happend that they are able to interop?

**Comment by gkdr** [comment]
Well, there aren't many devs converned with OMEMO right now, and they're all very talkative, so it's easy to reach a consensus :D Of course it's mostly the same except for some small but critical differences, talking over every little thing would be counterproductive.

In any case, it is now (5878cde5f0c71fd19b9d6f6851873dad0ae4b5da) possible to talk to the other clients! Changes were mostly in [libomemo](https://github.com/gkdr/libomemo), so be sure to get the newest version of it.

**Comment by Sur3** [comment]
I'm quite interessted in this discussion about standard conformity as i wondered why lurch is using Axalotl as the XEP-Standard has libolm instead, a there any plans to switch to standard-conform libolm in the future?

**Comment by gkdr** [comment]
Well, none of the other clients use Olm, so standard-conformity is not very useful right now.
In fact, the [new draft](https://github.com/xsf/xeps/pull/460) is trying to get rid of the need for a specific implementation.
