### ISSUE TITLE
recipe for target 'build/libomemo-conversations.o' failed

### ISSUE THREAD

**Issue by kriswema** [gkdr/lurch#30]
Hi! :) 
I'm trying to compile this on Debian, but have been failing to do so. Is there anything I've missed?

### System
* Debian Jessie 8.7 (stable)
* Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u1 (2017-02-22) x86_64

### Installed packages: apt-show-versions | egrep 'libpurple-dev|libmxml-dev|libxml2-dev|libsqlite3-dev|libgcrypt20-dev'
libgcrypt20-dev:amd64/jessie 1.6.3-2+deb8u2 uptodate
libmxml-dev:amd64/jessie 2.6-2 uptodate
libpurple-dev:all/jessie 2.11.0-0+deb8u1 uptodate
libsqlite3-dev:amd64/jessie 3.8.7.1-1+deb8u2 uptodate
libxml2-dev:amd64/jessie 2.9.1+dfsg1-5+deb8u4 uptodate

### make errors
I'm seeing some errors saying ‘mxmlGetParent’ undeclared, ‘mxmlGetNextSibling’ undeclared, ‘mxmlGetLastChild’ undeclared...
[Check the full make output here](https://github.com/gkdr/lurch/files/806028/pidgin-lurch.make.txt)

**Comment by gkdr** [comment]
Unfortunately, Debian stable comes with mxml 2.6, which is 8 years old. The functions you are missing were added in 2.7. 
Is there a way to tell Debian to consider packages from testing?

**Comment by kriswema** [comment]
@gkdr I've temporarily added the testing repository to upgrade to libmxml 2.10. It seems to compile without errors now, but I didn't test the build yet. 
If you don't want to deal with changing your sources.list, you can manually download the packages from Debian too, in which case you'll need [libmxml-bin](https://packages.debian.org/stretch/libmxml-bin), [libmxml-dev](https://packages.debian.org/stretch/libmxml-dev), and [libmxml1](https://packages.debian.org/stretch/libmxml1).
I'll close this for now, issue resolved. :) Thanks!
