### ISSUE TITLE
No working Makefile in pidgin-2.11.0/libpurple/plugins

### ISSUE THREAD

**Issue by chaoscommander** [gkdr/lurch#4]
Following your exact words, build doesn't complete. It fails at the last stage:

`*** Keine Regel, um "lurch.so" zu erstellen. Schluss. *** `
There is no makefile in the Purple plugin source path. I tried generating one but failed.

A friend said he would look into doing everything with cmake and might work on that later today.

Also, I had to edit the libomemo and axc makefiles, else they wouldn't work on my system (Gentoo Linux). I'm hesitating to do a pull request since the build still doesn't complete successfully without a working libpurple plugin makefile (and I have no idea how to write one).

**Comment by gkdr** [comment]
I have a suspicion - I think the makefile in that directory might only be generated when you build pidgin itself.
(The whole reason for this complicated build is that I didn't want to take that makefile apart as it is autogenerated and hard to read. I guess I did not expect it to be autogenerated only when pidgin is compiled.)

Are the other problems related to libtool? It claims it makes compiling on different platforms easier, but it seems it does the opposite (a friend also ran into libtool problems on macos). I'll look into getting rid of libtool and building everything without the Pidgin source today.

Thanks for trying :D

**Comment by chaoscommander** [comment]
Yes, they are. I had to add --tag=CC to each invocation of libtool or it would complain about the tag missing.
... What's funny is that now after successfully passing that part of the process, I can't reproduce this by removing the tag, not even by doing a "make clean" first.

**Comment by gkdr** [comment]
Okay, I completely changed the build process in 9a43d65cec604a9bdbf11a89e3388bee28148567.
Maybe this will work better for you (and everyone else...).

**Comment by gkdr** [comment]
Closing this because the pidgin tree is not in the build path any longer.
