### ISSUE TITLE
Lurch Updates for Windows

### ISSUE THREAD

**Issue by Urodela** [gkdr/lurch#44]
Im not sure if this is the right place to ask but anyway: Is there a way to get Lurch Updates for Windows? Im still on 0.6.3 since EionRobb doesnt upload any new Version anymore. Would be nice if "you" could provide a binary version for "no coders" like me.

Sorry for my nice english skills... have a nice day and sorry if theres another place to ask stuff like this which i dont know...

**Comment by gkdr** [comment]
I didn't try setting anything up on my Windows machine since Eion didn't seem to mind doing it, so I can't do it right away.
I will ask him if about it.

(Don't worry, it's the right place.)

**Comment by EionRobb** [comment]
There's a 0.6.5 build at https://eion.robbmob.com/lurch/ now

**Comment by gkdr** [comment]
@Urodela Well, in theory you could set up your machine [like this](https://developer.pidgin.im/wiki/BuildingWinPidgin) and then use Eion's patched makefile to try and do it yourself. In theory cross-compilation from "normal" Linux (i.e. not Cygwin) to Windows should also be possible, but I haven't tried.
However, there is no reason to worry about such a thing at the moment.

**Comment by Urodela** [comment]
@EionRobb & @gkdr >> Thank you very much! I really appreciate that, sorry for the disturbance... Alright, thanks for your work and have a nice Day!
