### ISSUE TITLE
Makefile or build description doesn't work

### ISSUE THREAD

**Issue by turion** [gkdr/lurch#5]
I did the following:

```
git clone git@github.com:gkdr/lurch.git
cd lurch
mkdir lib
cd lib
git clone git@github.com:gkdr/axc.git
cd ..
make
```

This doesn't work. The error is:

```
cd ./lib/axc && make axc-pic
make[1]: Entering directory '/home/turion/Install/lurch/lib/axc'
gcc -fPIC -std=c11 -Wall -Wextra -Wpedantic -Wstrict-overflow -fno-strict-aliasing -funsigned-char -D_XOPEN_SOURCE=700 -D_BSD_SOURCE -D_POSIX_SOURCE -D_GNU_SOURCE -fno-builtin-memset -c src/axc.c -o build/axc.o
In file included from /usr/include/inttypes.h:25:0,
                 from src/axc.c:1:
/usr/include/features.h:148:3: warning: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Wcpp]
 # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
   ^
src/axc.c:9:29: fatal error: axolotl/axolotl.h: No such file or directory
compilation terminated.
make[1]: *** [makefile:41: axc.o] Error 1
make[1]: Leaving directory '/home/turion/Install/lurch/lib/axc'
make: *** [makefile:36: axc] Error 2
```

I don't know where to put the proper files. Can you update the Makefile or explain in more detail how this should be built?

**Comment by gkdr** [comment]
It looks like you did not install libaxolotl-c. It comes with axc (again in the lib directory), its README has information on how to install that. I tried pointing out this step by saying to "install the libs' dependencies", but I probably should just make one step-by-step guide. Sorry, I know it's kind of a mess, but I did not anticipate much interest.

So in your case, after  yoo do `git clone git@github.com:gkdr/axc.git`, you do the following:
```
cd axc/lib/libaxolotl-c
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=ON ..
make
sudo make install
```

**Comment by turion** [comment]
Thanks for your answer! I somehow thought that if libaxolotl-c is in the local `lib` directory, it might be found as well.

Anything involving `sudo make install` is out of question for me (I'd like to keep my system clean and only let the package manager touch system-wide directories). Is there a way to compile and include it globally?

**Comment by gkdr** [comment]
`make` will create a static and a shared lib, afaik `make install` just puts the latter and the header files in the directories where the system can find them.
In fact I have been using the static lib most of the time, and now that I switched to compiling everything to object files, I could probably include the static lib just as well. I'll probably look into it later today.

**Comment by gkdr** [comment]
Okay, now just cloning the dependencies and typing `make` in the lurch dir should be enough.
(The lurch `make install` will just copy the .so to the libpurple plugin dir and doesn't need `sudo`.)

**Comment by gkdr** [comment]
I now also switched to including the other libs as submodules, hopefully making it even easier.

**Comment by aladar42** [comment]
I'm sorry if I'm being dense, but I have no knowledge of C... I tried to build this, but I get these errors:
http://pastebin.com/fjg6NDAj

Any idea what am I doing wrong?

**Comment by gkdr** [comment]
It seems that the package available for Debian contains the lib in the version 2.6, which is from 2009. The functions seem to have been added in version 2.7, from 2011. Even though I got an email about it I don't see the pull request, but in any case I don't think I should manually add snippets like that to my code to support libraries that are that old.
(You could install the newest mxml from source, that seems easier than doing this kind of patching.)

**Comment by gkdr** [comment]
@turion I am sure I fixed your issue, but was waiting for a comment. So in case you unsubscribed from this thread, I'm highlighting you to get your attention, otherwise I'll close this issue soon.

**Comment by turion** [comment]
Thanks! Sorry, I was busy with other things and I didn't catch up quick enough. I tried again and got much further. Now I'm at this error here (after calling `make` once already):

```
$ make
cd ./lib/libomemo && make
make[1]: Entering directory '/home/turion/Install/lurch/lib/libomemo'
Package mxml was not found in the pkg-config search path.
Perhaps you should add the directory containing `mxml.pc'
to the PKG_CONFIG_PATH environment variable
No package 'mxml' found
gcc -c src/libomemo.c -std=c11 -Wall -Wextra -Wpedantic -Wstrict-overflow -fno-strict-aliasing -funsigned-char -D_XOPEN_SOURCE=700 -D_BSD_SOURCE -fno-builtin-memset   -DOMEMO_XMLNS='"eu.siacs.conversations.axolotl"' -DOMEMO_NS_SEPARATOR='"."' -DOMEMO_NS_NOVERSION -fPIC -o build/libomemo-conversations.o
In file included from /usr/include/inttypes.h:25:0,
                 from src/libomemo.c:1:
/usr/include/features.h:148:3: warning: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Wcpp]
 # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
   ^
src/libomemo.c:7:32: fatal error: glib.h: No such file or directory
compilation terminated.
make[1]: *** [makefile:42: build/libomemo-conversations.o] Error 1
make[1]: Leaving directory '/home/turion/Install/lurch/lib/libomemo'
make: *** [makefile:48: lib/libomemo/build/libomemo-conversations.a] Error 2
```

This is really weird, since I definitely have the file at `/usr/include/glib-2.0/glib.h` and when I call `pkg-config --cflags --libs glib-2.0`, I get `-I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -lglib-2.0`, so no idea what's going wrong here.

**Comment by gkdr** [comment]
Oh, I didn't want to hurry you, just wondered if you're still interested at all still, but thanks for the quick reply.

I'm calling `pkg-config --cflags glib-2.0 sqlite3 mxml` in the makefile (since gcc has to know where those headers are too), and it seems that it cannot find mxml, and just returns an error for the whole command.
Is mxml (Mini-XML) also not available from your package manager? I was considering linking it statically since Debian stable has an 8 year old version that is missing some functions I use... Or replacing it by libxml2 entirely.

**Comment by turion** [comment]
Ah, now I understand! I installed it via the package manager and it
could be built, and activated! Thanks! I'll test it now.
