### ISSUE TITLE
cc: error: unrecognized command line option ‘-Wpedantic’

### ISSUE THREAD

**Issue by andyb9** [gkdr/lurch#50]
getting the following error on make
`
~/lurch# make
make -C "./lib/axc" build/libaxc-nt.a
make[1]: Entering directory `/root/lurch/lib/axc'
cc -fPIC -I./lib/libsignal-protocol-c/src -I/usr/include/glib-2.0 -I/usr/lib/i386-linux-gnu/glib-2.0/include    -std=c11 -Wall -Wextra -Wpedantic -Wstrict-overflow -fno-strict-aliasing -funsigned-char -fno-builtin-memset -D_XOPEN_SOURCE=700 -D_BSD_SOURCE -D_POSIX_SOURCE -D_GNU_SOURCE -DNO_THREADS -c src/axc.c -o build/axc-nt.o
cc: error: unrecognized command line option ‘-Wpedantic’
make[1]: *** [build/axc-nt.o] Error 1
make[1]: Leaving directory `/root/lurch/lib/axc'
make: *** [lib/axc/build/libaxc-nt.a] Error 2
`

**Comment by gkdr** [comment]
That's weird, what's your C compiler?
As that flag only enables more warnings, you could in theory just remove it. I suspect your compiler might not know some of the flags that are actually useful then too, though.

**Comment by andyb9** [comment]
> That's weird, what's your C compiler?

The C compiler is gcc, which is apparently a cross-compiler.

**Comment by gkdr** [comment]
Is it a bit old, maybe?
Does it work when you remove the flag? As I said, it just adds additional warnings and serves no real function here.

**Comment by andyb9** [comment]
seeing that i cant seem to compile it, can i then just copy the 

.so

to  /usr/lib/purple-2

---
if so can i get the .deb please :smile:

**Comment by gkdr** [comment]
What doesn't work? Did you try to remove `-Wpedantic` from [here](https://github.com/gkdr/axc/blob/032fba9c5610d33298cccaf400af9a8813b03f2f/makefile#L30)?

In any case, you should be able to use the `.so` from the [releases](https://github.com/gkdr/lurch/releases) page and put it in `~/.purple/plugins` (create the directory if it doesn't exist yet).

**Comment by andyb9** [comment]
Thanks for your help gkdr :)

The .so didnt work but i was finally able to build it and the resulting .so worked!

I had to remove -Wpedantic from 2 different 'makefile' in the build folder though before the error message went away.

**Comment by gkdr** [comment]
Glad it worked in the end!
I'm going to close this issue then.
