### ISSUE TITLE
rework README

### ISSUE THREAD

**Issue by gkdr** [gkdr/lurch#55]
The README needs some cleanup.

- [ ] Merge #45 
- [ ] Merge #51 
- [ ] Add table of contents with links
- [ ] Mention that it works fine in Finch (and maybe tell that to omemo.top)

**Comment by ccoenen** [comment]
Also, Debian Stable is now Stretch, which means that [`libmxml-dev`](https://packages.debian.org/search?keywords=libmxml-dev) is version 2.10!
