### ISSUE TITLE
Build system: defining CFLAGS breaks build

### ISSUE THREAD

**Issue by lachs0r** [gkdr/lurch#59]
Linux distributions usually add certain default compiler flags (like `-fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables`).
When trying to package this plugin, I noticed that having CFLAGS defined will override lurch’s own flags, breaking the build.

**Comment by gkdr** [comment]
Merging #58 would fix this issue, right?

**Comment by lachs0r** [comment]
Looks like it should.

**Comment by gkdr** [comment]
Closing as df33835 merged the references pull request.
