### ISSUE TITLE
Integration with Thunderbird

### ISSUE THREAD

**Issue by allo-** [gkdr/lurch#6]
Is there a possible integration with the libpurple chatclient in Thunderbird?

**Comment by gkdr** [comment]
I only used libpurple commands, so if Thunderbird implements them, I don't see why not. I don't know how/if plugins work there though, I'll have to look into it.

**Comment by gkdr** [comment]
Unfortunately, instantbird does not use the libpurple XMPP code, so it will not work.

**Comment by allo-** [comment]
Instantbird is another thing than the integration with thunderbird. Or do they share the same code for chatting?

**Comment by EionRobb** [comment]
Instantbird and Thunderbird use the same XMPP codebase written in Javascript, rather than using libpurple's XMPP client

**Comment by allo-** [comment]
Okay.

**Comment by manuc66** [comment]
Looking at https://github.com/bascht/omemo-top/blob/master/index.md there is an open issue for Instantbird : https://bugzilla.mozilla.org/show_bug.cgi?id=1237416
