### ISSUE TITLE
ABI Version conflict 2.12.x (need 2.10.x)

### ISSUE THREAD

**Issue by git-minix** [gkdr/lurch#67]
Got this error message in Pidgin: ABI Version conflict 2.12.x (need 2.10.x)

pidgin                                      1:2.10.12-0ubuntu5.2     
libpurple0                                  1:2.10.12-0ubuntu5.2 

on linux Mint 18.2 Cinnamon 64-bit

used the latest lurch version 0.6.5

It there a need to compile only with ABI Version 2.10 ?

**Comment by EionRobb** [comment]
@gkdr if you switch `PURPLE_MINOR_VERSION` for a lower version number, eg `8` then it'll allow plugins compiled against a newer libpurple to work with an older libpurple (as long as the functions you use were around in that version of libpurple)

@git-minix  You might be better to compile it yourself using the instructions on the Readme about how to compile

**Comment by gkdr** [comment]
I thought I ran into some problems there, but maybe I remember wrong. I'll try to see if it works.

**Comment by git-minix** [comment]
with a re-compile I've solved the issue
