### ISSUE TITLE
Can't send message to conversation client (but recieve)

### ISSUE THREAD

**Issue by treba123** [gkdr/lurch#68]
I'm trying to have a conversation between a conversion and a pidgin client. 
The conversation client can send messages to the pidgin client just fine, but when trying to send something back, I get:
`Even though an encrypted session exists, the recipient's devicelist is empty.The user probably uninstalled OMEMO, so you can add this conversation to the blacklist.`

I'm not sure if that's a bug from lurch or conversation, though.

**Comment by gkdr** [comment]
Are you sure it's not a server issue? I have heard that new versions of both ejabberd and Prosody came with weird PEP defaults, but I can't remember the details.
You could look in the Pidgin debug window if the devicelist is indeed empty to confirm this.

**Comment by treba123** [comment]
Hej, thanks for the answer. Somehow the error now disappeared and everything works with different contacts. So it seems to be alright :)
