### ISSUE TITLE
Create a Debian Package for Lurch

### ISSUE THREAD

**Issue by herbsmn** [gkdr/lurch#73]
Some projects, like the Tails OS, almost exclusively grab their code from offical Debian Packages so Lurch will likely never be used by them unless it is packaged in Debian. https://labs.riseup.net/code/issues/11541

**Comment by gkdr** [comment]
The problem is that the most important dependency, libsignal-protocol-c, is also not available from the package repos and I think if someone did make it available OWS would ask to take it down (I faintly remember them saying it's not ready yet).

**Comment by herbsmn** [comment]
Thanks for your response. 

I'm curious, how did the Gajim Omemo plugin get packaged in Debian if this libsignal-protocol-c issues exists? https://dev.gajim.org/gajim/gajim-plugins/wikis/OmemoGajimPlugin https://tracker.debian.org/pkg/gajim-omemo

**Comment by gkdr** [comment]
Might be related to the fact that there's no official Python implementation and it uses code ported by someone else. Maybe Debian just accepts a huge tarball that includes all the dependencies too, because I somehow doubt all the Python deps are also Debian packages, so maybe it's worth looking into that.

**Comment by DanScharon** [comment]
libsignal-protocol-c is now in debian testing: https://tracker.debian.org/pkg/libsignal-protocol-c

**Comment by gkdr** [comment]
I prioritize fixing bugs, and unfortunately there were a lot of them around still. But to be honest, there's so many issues I keep losing track of some, including this one, so thanks for asking again. I think I'll investigate this next. I wish GitHub had a way to assign a priority to issues.

**Comment by herbsmn** [comment]
@gkdr you're welcome for asking again. :-) I think you can use labels somehow to assign a prioritiy to issues. https://help.github.com/articles/about-labels/

**Comment by voidstarstar** [comment]
Tails now has an "Additional Software" feature that will allow users to automatically install packages from the Debian repositories.

Also, libsignal-protocol-c was added to stretch-backports.

**Comment by nemoinis** [comment]
I'd love to have lurch packaged on Debian too. Conversations (Android IM client) recently dropped OTR, so it's OMEMO O'nothing. :-)

**Comment by herbsmn** [comment]
@voidstarstar, yeah, it'd be great to see Lurch in stretch-backports for use in Tails! @gkdr, any chance you've had some time to look into doing a debian package?

**Comment by varac** [comment]
There's already a [debian request for packaging for lurch](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=905883). But until now nobody picked it up, so it would be good to coordinate with potential debian maintainers through their bug tracker.

**Comment by gkdr** [comment]
by now, someone else did it (and i'm infinitely thankful for that).

see here: https://packages.debian.org/unstable/net/purple-lurch
