### ISSUE TITLE
Sending messages to one's own self results in annoying warnings

### ISSUE THREAD

**Issue by leedoyle** [gkdr/lurch#76]
The warning:

> There was an error **decrypting** an OMEMO message addressed to this device. See the debug log for details.

update: as it turned out there **was a worse bug** around. When using pidgin 2.10.12 on ubuntu 16.04 w/ lurch.so and  https://github.com/Junker/purple-xmpp-http-upload/issues/7 files uploaded per http upload plugin (XEP-0363) are not encrypted at all.

**Comment by leedoyle** [comment]
It turned out there was a worse bug around. When using pidgin 2.10.12 on ubuntu 16.04 w/ lurch.so and  https://github.com/Junker/purple-xmpp-http-upload/issues/7 files uploaded per http upload plugin (XEP-0363) are not encrypted.

**Comment by gkdr** [comment]
I'm not sure how the file transfer thing is related to sending files to yourself, but as noted in the other issue, file transfers are not part of the OMEMO XEP and therefore not of this plugin (as of now).

As for sending messages to yourself, did you try the dev branch?

**Comment by gkdr** [comment]
I have reproduced the warning based on the master branch, and then tried the dev branch where it is not present. Seems fixed to me, if it's not, feel free to reopen.
