### ISSUE TITLE
Pidgin plugin don't work

### ISSUE THREAD

**Issue by sybot99** [gkdr/lurch#77]
Server of both users: jabber.cat
1 user: pidgin + lurch.dll plagin
2 user: iOS 11 + ChatSecure

The window in pidgin doesn't show any information about the OMEMO is turn on and messages to ChatSecure comes no crypted. If I send message from ChatSecure to Pidgin - it doesn't come at all

**Comment by n0rc** [comment]
What happens if you type `/lurch help` in a message window in Pigdin?

**Comment by gkdr** [comment]
Can you see this plugin in the plugin list?

**Comment by gkdr** [comment]
I'll close this for inactivity. Feel free to reopen with more info.
