### ISSUE TITLE
Can't send encrypted messages to Gajim

### ISSUE THREAD

**Issue by kozross** [gkdr/lurch#78]
I'm getting something very similar to #70. When I try to send a message, I get this:

    Even though an encrypted session exists, the recipient's devicelist is empty.The user probably uninstalled OMEMO, so you can add this conversation to the blacklist.

The message does not go through in such a case. This is on a server that definitely supports PEP (which I run), and the other user is on Gajim. The other user tried resetting their OMEMO keys, and that helped once, but then this issue happened a second time (with Finch on a different machine) and this time a reset did nothing.

**Comment by gkdr** [comment]
I posted the query to check if there is a devicelist saved on the server in the issue you linked. Could you please try that? To get to Pidgin's XMPP console, you first have to activate it in the plugin list, after which you can access it via _Tools -> XMPP Console_.

**Comment by kozross** [comment]
I'm on Finch, not Pidgin - how would I find this? Also, what's the query exactly?

**Comment by gkdr** [comment]
I checked and it's actually not available in Finch, it seems to depend on GUI functionality too much. But it doesn't have to be the same client the plugin is installed on, you can use any client connected to your account to ask the XMPP server for some info. Do you have access to a computer that can run Pidgin?

I probably said it weirdly, but I tried to tell you that I posted the exact query in #70. I probably should add some sort of troubleshooting section somewhere and copy it there. In any case, here it is, just replace the JID with your friend's.
```
<iq type='get'
    to='b@localhost'
    id='whatever123'>
  <pubsub xmlns='http://jabber.org/protocol/pubsub'>
    <items node='eu.siacs.conversations.axolotl.devicelist'/>
  </pubsub>
</iq>
```

**Comment by kozross** [comment]
If Lurch doesn't work in Finch, it's not really useful to me. It's really disappointing that Finch is basically a second-class citizen in the Purple ecosystem, but I guess there isn't much I can do about it. Thanks - closing now.

**Comment by EionRobb** [comment]
@kozross no, @gkdr is saying that the XMPP Console plugin doesn't work on Finch.  Lurch does though :)
