### ISSUE TITLE
Writing to MUC fails when re-joining chat

### ISSUE THREAD

**Issue by quazgar** [gkdr/lurch#81]
When writing a message to a MUC after rejoining a room which I joined and creates previously, I get the error message:

> (06:15:24 PM) There was an error encrypting the message and it was not sent. You can try again, or try to find the problem by looking at the debug log.

The log says:
> (18:15:24) lurch: lurch_message_encrypt_groupchat: no entry in ht for xxx@yyy.net!
 (0)
(18:15:24) g_log: xmlnode_to_str_helper: assertion 'node != NULL' failed
(18:15:24) g_log: jabber_send_raw: assertion 'data != NULL' failed

There's one more user in the room the whole time which uses Conversations.  I am using Pidgin (libpurple 2.12.0) on Gentoo Linux.

**Comment by gkdr** [comment]
When doing the (even more experimental than the rest) groupchat implementation I had to work around Pidgin by manually parsing the presence XMPP stanzas and create 2 levels of hashtables to store the information I need as the XMPP protocol plugin does not fill the data structure with the information.
Since this is the 3rd or 4th issue with the MUC, I assume something is going wrong when doing this. 

Can you open the debug window while you join the MUC and copy the raw XML for me? As just said, I'm mainly looking for the `<presence>` stanzas.  Also, do you know which server software and version the one you use is running? I have never been able to reproduce this locally running Prosody.

**Comment by quazgar** [comment]
Hi, this is the output for `/part`, joining again, trying to send a message and `/part` again.  If you want to know details about the server, you could ask the friendly people at support@netzguerilla.net, I think they might be interested in helping out at encryption related issues.

> (19:05:09) jabber: Sending (ssl) (quazgar@netzguerilla.net/576f9c6a-ebc8-4059-921b-2bfeed4a4815): <presence to='gruenes_haus_anner_ecke@conference.netzguerilla.net/quazgar' type='unavailable'/>
(19:05:09) jabber: Recv (ssl)(283): <presence type='unavailable' to='quazgar@netzguerilla.net/576f9c6a-ebc8-4059-921b-2bfeed4a4815' from='gruenes_haus_anner_ecke@conference.netzguerilla.net/quazgar'><x xmlns='http://jabber.org/protocol/muc#user'><item affiliation='none' role='none'/><status code='110'/></x></presence>
(19:05:09) server: Leaving room: gruenes_haus_anner_ecke@conference.netzguerilla.net

> (19:05:28) GLib: Source ID 2113 was not found when attempting to remove it
(19:05:30) gtkconv: setting active conversation on toolbar 0xdef150
(19:05:30) jabber: Sending (ssl) (quazgar@netzguerilla.net/576f9c6a-ebc8-4059-921b-2bfeed4a4815): <presence to='gruenes_haus_anner_ecke@conference.netzguerilla.net/quazgar'><priority>1</priority><c xmlns='http://jabber.org/protocol/caps' node='http://pidgin.im/' hash='sha-1' ver='+mMSzw36s9OAOFqAJrTTYb2o+2I=' ext='voice-v1 camera-v1 video-v1'/><x xmlns='http://jabber.org/protocol/muc'><password>wiese28</password></x></presence>
(19:05:30) jabber: Recv (ssl)(902): <presence xml:lang='en' to='quazgar@netzguerilla.net/576f9c6a-ebc8-4059-921b-2bfeed4a4815' from='gruenes_haus_anner_ecke@conference.netzguerilla.net/ranapatito'><c hash='sha-1' ver='mz1I+PanXOmkFwo0w3D1+w0jdpA=' node='http://conversations.im' xmlns='http://jabber.org/protocol/caps'/><x xmlns='http://jabber.org/protocol/muc#user'><item role='moderator' affiliation='owner'/></x></presence><presence to='quazgar@netzguerilla.net/576f9c6a-ebc8-4059-921b-2bfeed4a4815' from='gruenes_haus_anner_ecke@conference.netzguerilla.net/quazgar'><priority>1</priority><c hash='sha-1' ext='voice-v1 camera-v1 video-v1' ver='+mMSzw36s9OAOFqAJrTTYb2o+2I=' node='http://pidgin.im/' xmlns='http://jabber.org/protocol/caps'/><x xmlns='http://jabber.org/protocol/muc#user'><item jid='quazgar@netzguerilla.net/576f9c6a-ebc8-4059-921b-2bfeed4a4815' affiliation='none' role='participant'/><status code='110'/></x></presence>
(19:05:30) jabber: Sending (ssl) (quazgar@netzguerilla.net/576f9c6a-ebc8-4059-921b-2bfeed4a4815): <iq type='get' id='purple3354547d' to='gruenes_haus_anner_ecke@conference.netzguerilla.net'><query xmlns='http://jabber.org/protocol/disco#info' node='http://jabber.org/protocol/muc#traffic'/></iq>
(19:05:30) jabber: Ignoring exts in new-style caps from gruenes_haus_anner_ecke@conference.netzguerilla.net/quazgar
(19:05:30) jabber: Recv (ssl)(263): <iq id='purple3354547d' type='error' to='quazgar@netzguerilla.net/576f9c6a-ebc8-4059-921b-2bfeed4a4815' from='gruenes_haus_anner_ecke@conference.netzguerilla.net'><error type='cancel'><service-unavailable xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/></error></iq>

> (19:05:40) lurch: lurch_message_encrypt_groupchat: no entry in ht for gruenes_haus_anner_ecke@conference.netzguerilla.net!
 (0)
(19:05:40) g_log: xmlnode_to_str_helper: assertion 'node != NULL' failed
(19:05:40) g_log: jabber_send_raw: assertion 'data != NULL' failed

> (19:05:45) jabber: Sending (ssl) (quazgar@netzguerilla.net/576f9c6a-ebc8-4059-921b-2bfeed4a4815): <presence to='gruenes_haus_anner_ecke@conference.netzguerilla.net/quazgar' type='unavailable'/>
(19:05:45) jabber: Recv (ssl)(283): <presence type='unavailable' to='quazgar@netzguerilla.net/576f9c6a-ebc8-4059-921b-2bfeed4a4815' from='gruenes_haus_anner_ecke@conference.netzguerilla.net/quazgar'><x xmlns='http://jabber.org/protocol/muc#user'><item affiliation='none' role='none'/><status code='110'/></x></presence>
(19:05:45) server: Leaving room: gruenes_haus_anner_ecke@conference.netzguerilla.net

**Comment by gkdr** [comment]
The important part is the following:
```XML
<presence 
    xml:lang='en' 
    to='quazgar@netzguerilla.net/576f9c6a-ebc8-4059-921b-2bfeed4a4815' 
    from='gruenes_haus_anner_ecke@conference.netzguerilla.net/ranapatito'>
  <c 
      hash='sha-1' ver='mz1I+PanXOmkFwo0w3D1+w0jdpA='
      node='http://conversations.im' 
      xmlns='http://jabber.org/protocol/caps'/>
  <x xmlns='http://jabber.org/protocol/muc#user'>
    <item role='moderator' affiliation='owner'/>
  </x>
</presence>
```
As you can see, there is no `jid` attribute in the `item` element, that means the room is anonymous. OMEMO does not work with anonymous rooms (actually it might with the right PEP config but iirc the config capabilities aren't fully implemented, might have changed by now though). Sorry, should have thought of that earlier. Can you try again after setting the room to non-anonymous?

**Comment by gkdr** [comment]
@quazgar, did you try again with a non-anonymous room?

**Comment by gkdr** [comment]
Actually, sorry for highlighting you - I changed the MUC implementation so this is not longer relevant either way. If the issue still persists, please open a new issue.
