### ISSUE TITLE
The device 1234567890 owned by alice@host.invalid does not have a bundle and will be skipped.

### ISSUE THREAD

**Issue by norpol** [gkdr/lurch#83]
Dear lurch friends,
When I'm chatting with a friend who happens to use OMEMO with Gajim on a self hosted jabber instance, every message I'm sending I'm receiving a big red error response stating:
> The device 1234567890 owned by alice@host.invalid does not have a bundle and will be skipped. The owner should fix this, or remove the device from the list.

This only happens on sending messages, and doesn't happen when I'm receiving messages. Sorry if this is a duplicate, I've searched a bit in the Issues here, but gave up eventually. Maybe a [github issue template](https://blog.github.com/2016-02-17-issue-and-pull-request-templates/) might be a nice thing to have.

Here is some debug output from Help => Debug Window (note: I've added some newlines and formatted some of the XML output manually:

```
(20:51:40) Lurch: [AXC INFO] axc_init: initializing axolotl client
(20:51:40) lurch: [AXC DEBUG] axc_init: created and set axolotl context
(20:51:40) lurch: [AXC DEBUG] axc_init: set axolotl crypto provider
(20:51:40) lurch: [AXC DEBUG] axc_init: created store context
(20:51:40) lurch: [AXC DEBUG] axc_init: set store context
(20:51:40) lurch: [AXC INFO] axc_init: done initializing axc
(20:51:40) lurch: retrieved devicelist for albo@host.invalid:
<publish node="eu.siacs.conversations.axolotl.devicelist"><item><list
xmlns="eu.siacs.conversations.axolotl"><device id="224766220" /><device
id="462067157" /><device id="01234567890" /></list></item></publish>
(20:51:40) lurch: retrieved own devicelist:
<publish node="eu.siacs.conversations.axolotl.devicelist"><item><list
xmlns="eu.siacs.conversations.axolotl"><device id="1804452568" /></list></item></publish>
(20:51:40) lurch: lurch_msg_finalize_encryption: albo@host.invalid has device without session 01234567890, requesting bundle
(20:51:40) lurch: lurch_bundle_request_do: me@other.invalid/resourceWithÜnicode is requesting bundle from albo@host.invalid:01234567890
(20:51:40) jabber: Sending (ssl) (me@other.invalid/resourceWithÜnicode): <iq type='get' to='albo@host.invalid' id='albo@host.invalid#01234567890#2860998'><pubsub xmlns='http://jabber.org/protocol/pubsub'><items node='eu.siacs.conversations.axolotl.bundles:01234567890' max_items='1'/></pubsub></iq>
(20:51:40) lurch: lurch_bundle_request_do: ...request sent
(20:51:40) g_log: xmlnode_to_str_helper: assertion 'node != NULL' failed
(20:51:40) g_log: jabber_send_raw: assertion 'data != NULL' failed
(20:51:40) lurch: [AXC INFO] axc_init: initializing axolotl client
(20:51:40) lurch: [AXC DEBUG] axc_init: created and set axolotl context
(20:51:40) lurch: [AXC DEBUG] axc_init: set axolotl crypto provider
(20:51:40) lurch: [AXC DEBUG] axc_init: created store context
(20:51:40) lurch: [AXC DEBUG] axc_init: set store context
(20:51:40) lurch: [AXC INFO] axc_init: done initializing axc
(20:51:40) g_log: invalid source position for vertical gradient
(20:51:40) jabber: Recv (ssl)(206): <iq from='albo@host.invalid' to='me@other.invalid/resourceWithÜnicode' id='albo@host.invalid#01234567890#2860998' type='error'><error type='cancel'><item-not-found xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/></error></iq>
(20:51:40) lurch: lurch_bundle_request_cb: pl@jabber.metalab.at received bundle update from albo@host.invalid:01234567890
(20:51:40) lurch: [AXC INFO] axc_init: initializing axolotl client
(20:51:40) lurch: [AXC DEBUG] axc_init: created and set axolotl context
(20:51:40) lurch: [AXC DEBUG] axc_init: set axolotl crypto provider
(20:51:40) lurch: [AXC DEBUG] axc_init: created store context
(20:51:40) lurch: [AXC DEBUG] axc_init: set store context
(20:51:40) lurch: [AXC INFO] axc_init: done initializing axc
(20:51:40) lurch: lurch_msg_encrypt_for_addrs: trying to encrypt key for 3 devices
(20:51:40) lurch: lurch_key_encrypt: encrypting key for albo@host.invalid:462067157
(20:51:40) lurch: lurch_key_encrypt: encrypting key for albo@host.invalid:224766220
(20:51:40) xmlnode: XML parser error for xmlnode 0x56364c8d2b90: Domain 3, code 100, level 1: xmlns: URI eu.siacs.conversations.axolotl is not absolute
(20:51:40) lurch: sending encrypted msg
(20:51:40) jabber: Sending (ssl) (me@other.invalid/resourceWithÜnicode): 
<message type='chat' id='purplee2c6b374' to='albo@host.invalid'>
	<active xmlns='http://jabber.org/protocol/chatstates'/>
	<encrypted xmlns='eu.siacs.conversations.axolotl'>
		<header sid='1804452568'>
				<key rid='224766220'>REMOVED_CONTENT[...]=</key>
				<key rid='462067157'>REMOVED_TOO[...]==</key>
		<iv>25O[...]==</iv>
		</header>
		   <payload>[...]==</payload>
	</encrypted>
	<encryption xmlns='urn:xmpp:eme:0' namespace='eu.siacs.conversations.axolotl' name='OMEMO'/>
	<store xmlns='urn:xmpp:hints'/>
</message>
```

Input into XMP Console (note, host is already offline):

```
<iq type='get' to='albo@host.invalid' id='whatever123'>
  	<pubsub xmlns='http://jabber.org/protocol/pubsub'>
    		<items node='eu.siacs.conversations.axolotl.devicelist'/>

  </pubsub>
</iq>
```

Response:
```
<iq from='albo@host.invalid' to='me@other.invalid/resourceWithÜnicode' id='whatever123' type='result'>
	<pubsub xmlns='http://jabber.org/protocol/pubsub'>
		<items node='eu.siacs.conversations.axolotl.devicelist'>
			<item id='1'>
				<list xmlns='eu.siacs.conversations.axolotl'>
					<device id='1234567890'/>
					<device id='224766220'/>
					<device id='462067157'/>
				</list>
			</item>
		</items>
	</pubsub>
</iq>
```

PS: Is it necessary to remove the `<key></key>` and `<device id=""/>` content or is it save to share here?

Thank you in advance! :-)

**Comment by gkdr** [comment]
Hi, just looking at the log it seems like it is working as expected and it's just a case of bad UI.
The devicelist you posted contains 3 devices - does your friend actually have 3 devices? The key log statement is this one:
```
(20:51:40) jabber: Recv (ssl)(206): <iq from='albo@host.invalid' to='me@other.invalid/resourceWithÜnicode' id='albo@host.invalid#01234567890#2860998' type='error'><error type='cancel'><item-not-found xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/></error></iq>
```
So the actual server replies that the node containing the bundle (which contains all the public keys necessary to establish a session) is not there. PEP nodes are usually not permanent and e.g. get deleted after a server restart, so if there is no device it probably did not upload a bundle either. I don't know why the device would still show up in the devicelist, but maybe it's some weird timing thing or a "feature" of the Gajim implementation (it might upload the whole cached list of own devices instead of just checking if it itself is contained in the list).

I hope that cleared it up a bit, and you should really just do as the warning message says and tell your friend to clean up the devicelist. I just thought that silently dropping the message is even worse UI, but maybe one message per conversation is enough, instead of telling you every single message. 

If your friend actually owns 3 devices, we can investigate this further, but the bundle for one device is simply not there, and it seems to have worked for the other 2.

>PS: Is it necessary to remove the <key></key> and <device id=""/> content or is it save to share here?

The key is encrypted with the libsignal session, so it is not secret. The device ID ist just an (insecurely random) identifier and also not secret.

**Comment by norpol** [comment]
Thank you for your detailed response, the next time we chatted again the issue went away.
We can't exactly tell where the third device was coming from and the issue suddenly stopped appearing, it's possible that it was an old Pidgin key - hopefully nothing suspicious ;-).
