### ISSUE TITLE
Cannot start omemo conversation (though "omemo available")

### ISSUE THREAD

**Issue by faustdotmef** [gkdr/lurch#85]
checked /help lutch but there is no command to start omemo in 1 to 1 conversation. only for group chats.

**Comment by gkdr** [comment]
Have you tried just sending a message?
As the [usage instructions in the README](https://github.com/gkdr/lurch#general) states:
>[...] you do not have to activate it specifically for each conversation partner you want to use it with, unlike with e.g. OTR. If it detects that the other side is using OMEMO (by the existence of an OMEMO devicelist), the conversation will be encrypted automatically. [...]

**Comment by faustdotmef** [comment]
oh. sorry. i just expected same interface as in otr plugin. where you can turn cryptography on and off.

**Comment by gkdr** [comment]
No problem, I realize it can be a bit confusing at first. I'm going to close the issue then, but if anything else comes up feel free to open a new issue or continue commenting here if it seems fitting enough.
