### ISSUE TITLE
Feature request: /lurch status command

### ISSUE THREAD

**Issue by xi** [gkdr/lurch#86]
I would generally like a better indicator like in #66. As a first step, a new command `/lurch status` would be nice that simply tells you wether the current conversation is encrypted.

**Comment by gkdr** [comment]
I can probably reuse this later for displaying verification information, and also to give more usage hints to prevent stuff like #85, so I think it's a good idea.

**Comment by Kudalufi** [comment]
A far better idea is to have an actual UI for lurch, the same as every other messenger that supports OMEMO (Conversations, Pix-Art, Gaijim).  A lock symbol is what is normally used to indicate status.

Additionally, a way to activate/deactivate encryption is needed.  Some clients handle file transfers over an encrypted connection badly, and it is necessary to turn off encryption to transfer files.

**Comment by adrianheine** [comment]
Those are good points! They are separate features, though, and should be tracked in separate issues.

**Comment by gkdr** [comment]
implemented with c2554555cdec57dda25db144267d585580ec0704 :slightly_smiling_face: 

@VA1DER the command is implemented via the (also new) API, so now that is possible and of course a good idea!
