### ISSUE TITLE
Coredump at startup on conferences reconnection

### ISSUE THREAD

**Issue by albatros69** [gkdr/lurch#87]
Hello,

After a few moments testing lurch and OMEMO, I cannot launch pidgin anymore. Seems to crash on a some conferences with the following debug message:
(18:57:07) jabber: XML parser error for JabberStream 0x5577bb437050: Domain 3, code 100, level 1: xmlns: URI eu.siacs.conversations.axolotl is not absolute
(18:57:07) GLib: g_hash_table_lookup: assertion 'hash_table != NULL' failed
(18:57:07) lurch: [AXC INFO] axc_init: initializing axolotl client(18:57:07) lurch: [AXC DEBUG] axc_init: created and set axolotl context(18:57:07) lurch: [AXC DEBUG] axc_init: set axolotl crypto provider(18:57:07) lurch: [AXC DEBUG] axc_init: created store context(18:57:07) lurch: [AXC DEBUG] axc_init: set store context(18:57:07) lurch: [AXC INFO] axc_init: done initializing axcPidgin 2.12.0 a planté et a essayé de créer un fichier "core".
Ceci est un problème logiciel et n'est pas dû à une
utilisation erronée du logiciel de votre part.

Si vous pouvez reproduire ce plantage, veuillez en
informer les développeurs en rapportant le problème sur
http://developer.pidgin.im/simpleticket/

Veuillez bien préciser ce que vous faisiez à cet instant et
attacher la pile d'appel (backtrace) obtenue depuis le fichier
core. Si vous ne savez pas comment procéder, veuillez suivre
les indications sur
http://developer.pidgin.im/wiki/GetABacktrace
dns[2745]: Oops, father has gone, wait for me, wait...!
Abandon

Let me know if I can help troubleshoot further.
Regards,

**Comment by gkdr** [comment]
Hi, thanks for the report. This is probably related to #65, so improper handling of messages that arrive as part of the MUC "history" feature (if I understand correctly). I'm not sure if you can just disable this feature in Pidgin, but if so, maybe you can try that.

**Comment by albatros69** [comment]
I just did. Seems to have solve my particular issue: no more crash at startup. I'm currently validating that I can post in the conversion room and see others' posts as well. I keep you posted about the outcome.
Thanks for the support anyway!

**Comment by gkdr** [comment]
I'm not sure why, but sometimes the `<presence>` doesn't get parsed. I often got that error myself while developing the bugfixes but ignored it for now as a restart fixed it (and no one else had reported it at the time, but I got it with 0.6.6 too). I made a seperate issue for that: #92.  But since it doesn't crash anymore, I'll close this one.
