### ISSUE TITLE
It simply doesn't encrypt anything.

### ISSUE THREAD

**Issue by jesse-git** [gkdr/lurch#93]
Pidgin 2.12.0
lurch 0.6.6
carbons 0.1.4
I'm using an XMPP server with OMEMO support. OMEMO works fine on the same accounts when using clients other than pidgin+lurch.

I've tried so many different things to get this to work properly. It simply doesn't. There is no window title change and all messages are sent unencrypted. The plugins are shown as enabled. Please advise. Thank you.

**Comment by gkdr** [comment]
If the window title does not change at all, it might not have been loaded properly. When you open the plugin window and click on the lurch plugin and which is supposedly loaded and open up the details, is there a red error message somewhere? What happens when you type `/lurch help`?

Or does it not change away from "OMEMO (available)"? Either way, can you open up the debug log and show me what happens there when you send a message?

**Comment by jesse-git** [comment]
> If the window title does not change at all, it might not have been loaded properly. When you open the plugin window and click on the lurch plugin and which is supposedly loaded and open up the details, is there a red error message somewhere?

No error message there. Everything under details appears to be normal.

> What happens when you type /lurch help?

It works! No change as far as encryption, but the command works.

> Or does it not change away from "OMEMO (available)"?

I have never seen "OMEMO (available)" anywhere in pidgin.

> Either way, can you open up the debug log and show me what happens there when you send a message?

I will do this later today.

**Comment by jesse-git** [comment]
Attached are both the XMPP console logs and the pidgin debug window log. Here was my procedure:
1. Disabled all accounts other than the one being tested
2. Enabled logging
3. Connected to account
4. Sent a "test message". Not sure if I captured my friend also attempting to send a message or not.
5. Copied both logs to file
6. Replaced all identifiers with `STRIPPED` or some variant starting with `STRIPPED`. Also made a few `SNIP`s.

[debug log.txt](https://github.com/gkdr/lurch/files/1926087/debug.log.txt)
[xmpp log.txt](https://github.com/gkdr/lurch/files/1926088/xmpp.log.txt)

**Comment by jesse-git** [comment]
I did, at one point in a previous conversation. I'm not sure if it was for the same buddy that I used for capturing the log files (but according to the readme, it shouldn't matter?). It responded with something about the option only being valid for MUCs, like the readme says. (I tried to enable it without knowing it only applied to MUCs because I hadn't read that far in the readme yet.) In any case, lurch had the same behavior (no signs in UI that it's working) prior to me issuing the enable command.

**Comment by gkdr** [comment]
I think I forgot to ask another important question - which OS you are using. And based on the log I think you are using Windows, so the issue is the same as #88, Can you try again now?

**Comment by jesse-git** [comment]
It works! Yeah, Windows 10. I now see "(OMEMO available)" and afterwards "(OMEMO)". Sending and receiving works perfectly, carbons work, message receipts, and it even cooperates well with the OTR plugin if the "Automatically initiate private messaging" in the OTR plugin is turned off.

The new dll version still says 0.6.6, so you might want to bump it.

Thanks again!

**Comment by gkdr** [comment]
Well, there was a compile flag missing in the Windows version, the code didn't change at all, so I don't think changing the version is the right way to go. So unless someone has a better idea, I'll just hope people will find this now appropriately named issue.
