### ISSUE TITLE
Windows classifies lurch 0.6.7 prebuilt DLL as malware

### ISSUE THREAD

**Issue by NattyNarwhal** [gkdr/lurch#95]
....and immediately removes it, no questions asked. It classifies it as `Trojan:Win32/Spursint.F!d`. Is this a false positive, or is the build machine compromised or something?

This is fully patched Windows 10 amd64.

**Comment by EionRobb** [comment]
False positives are very common in the world of libpurple plugins :( 
9 times out of 10, forcing an update of virus definitions will resolve it, otherwise I'll submit to Microsoft for evaluation. 

If in doubt, use virustotal.com on the url to see what other virus checkers say

**Comment by EionRobb** [comment]
https://www.virustotal.com/#/url/62b448964d7f96b413621d8d3e83baa0c188d774c73fcf619c4572110a5c0125/detection is saying 0/67 

Probably worth updating virus definitions and trying again

**Comment by jsamyth** [comment]
Submitted lurch.dll to microsoft, not heard back,  
At first, simply attempting to download it triggered windows defender.  Bypassing that (hey, its just windows, who cares), I was able to get it installed, but any attempt to send using pigin caused crash, and error log auto-send to microsoft,
Used latest Microsoft Defender definitions as of this posting date (02May2018)

**Comment by gkdr** [comment]
Since I'm not sure how to fix this and this issue is related to an older version, I'm going to close this issue.
