### ISSUE TITLE
use libxmpp on SUSE

### ISSUE THREAD

**Issue by kolAflash** [gkdr/lurch#98]
I'm running openSUSE 42.3 and it looks like I need the same compilation switch as RedHat.

```
diff --git a/Makefile b/Makefile
index 222c368..f4c20d8 100644
--- a/Makefile
+++ b/Makefile
@@ -41,10 +41,12 @@ PKGCFG_L=$(shell $(PKG_CONFIG) --libs sqlite3 mxml) \
         $(XML2_LDFLAGS) \
         $(LIBGCRYPT_LDFLAGS)
 
+LJABBER= -ljabber
 ifneq ("$(wildcard /etc/redhat-release)","")
        LJABBER= -lxmpp
-else
-       LJABBER= -ljabber
+endif
+ifneq ("$(grep SUSE /etc/issue)","\n")
+       LJABBER= -lxmpp
 endif
 
 HEADERS=-I$(HDIR)/jabber -I$(LOMEMO_SRC) -I$(AXC_SRC) -I$(AX_DIR)/src
```

**Comment by gkdr** [comment]
Thanks, I'll add that.

**Comment by sledz** [comment]
I've prepared a slightly modified, ready to merge pull request for this.

**Comment by XRevan86** [comment]
Hi, I'm a maintainer of Pidgin in openSUSE and I just want to say that this is unnecessary starting with openSUSE Leap 15.0.
And that there's a purple-lurch package in the [network:pidgin](https://build.opensuse.org/project/show/network:pidgin) project :-).

**Comment by gkdr** [comment]
assuming this can be closed then :slightly_smiling_face:
